version: "2"
services: 
  caddy:  
    image: joshix/caddy
    links:
      - rstudio
      - milad 
      - allie
      - netdata 
    volumes:
      - ./site/:/var/www/html
      - ./.caddy/:/.caddy
    ports:
      - 80:80
      - 443:443
    restart: always

  rstudio:
    image: cboettig/labnotebook 
    env_file: rstudio.password 
    volumes:
      - $HOME/projects:/home/rstudio/projects
    restart: always

  netdata:
    image: titpetric/netdata  
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
    restart: always



