version: '2'

services: 
  caddy:  
    image: joshix/caddy
    links:
      - drone-server
   ## public files in site, .caddy holds letsencrypt certs 
    volumes:
      - ./site/:/var/www/html
      - ./.caddy/:/.caddy
    ports:
      - 80:80
      - 443:443
    restart: always

  drone-server:
    image: drone/drone:0.7
#    ports:
#      - 80:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    env_file: ./private_env.sh

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./private_env.sh


