version: '2'

services:
  caddy:
    image: abiosoft/caddy
   ## public files in site, .caddy holds letsencrypt certs
    volumes:
      - ./site/Caddyfile:/etc/Caddyfile
      - ./.caddy/:/root/.caddy
    ports:
    # - 80:80
      - 443:443
    restart: always
    environment:
      - ACME_AGREE=true

  rstudio:
    image: rocker/geospatial 
    restart: always
    volumes:
      - $HOME/rstudio_users:/home/
      - /vol_c:/home/shared
    env_file: ./private_env.sh

  monitor:
    image: titpetric/netdata
    restart: always
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
    ports:
      - 19999:19999

  mariadb:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=password
  postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password




