version: "2"
services: 
  caddy:  
    image: joshix/caddy
    links:
      - carl
      - kari 
      - millie 
      - allie
      - netdata 
    volumes:
      - ./site/:/var/www/html
      - ./.caddy/:/.caddy
    ports:
      - 80:80
      - 443:443
    restart: always

  allie:
    image: cboettig/labnotebook
    env_file: .password
    volumes:
      - $HOME/allie:/home/rstudio/projects
    restart: always

  millie:
    image: cboettig/labnotebook
    env_file: .password
    volumes:
      - $HOME/millie:/home/rstudio/projects
    restart: always

  kari:
    image: cboettig/labnotebook 
    env_file: .password 
    volumes:
      - $HOME/kari:/home/rstudio/projects
    restart: always


  carl:
    image: cboettig/labnotebook 
    env_file: .password 
    volumes:
      - $HOME/projects:/home/rstudio/projects
      - $HOME/services/site/logs:/home/rstudio/logs
    restart: always

  netdata:
    image: titpetric/netdata  
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
    restart: always

  mariadb:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=password
  postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password

  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
#    ports:
#      - "8890:8890"

