version: '2.3'

services:
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/data
    ports:
      - 80:80
      - 443:443
    restart: always

  rstudio:
    image: rocker/geospatial
    restart: always
    volumes:
      - home:/home
    env_file: ./private_env.sh

volumes:
  home:

#  monitor:
#    image: titpetric/netdata
#    restart: always
#    cap_add:
#      - SYS_PTRACE
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - ./netdata.conf:/etc/netdata/netdata.conf
#    ports:
#      - 19999:19999
##
## FIXME consider binding these to volume on /media/cboettig/ExtraDrive1
#  mariadb:
#      image: mariadb
#      environment:
#          - MYSQL_ROOT_PASSWORD=password
#  postgres:
#      image: postgres
#      environment:
#          - POSTGRES_PASSWORD=password




