version: '2.3'

# an example docker-compose mechanism with caddy
services:
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/root/.caddy
    ports:
      - 0.0.0.0:443:443
    restart: always

  rstudio:
    image: rocker/geospatial
    restart: always
    volumes:
    environment:
      - PASSWORD=yourpasswordhere
